### PR TITLE
Fix test failure on Python 3.12 (fixes #298)

### LINKED ISSUE #298: Test failure on Python 3.12 beta
While this was encountered on a separate branch from main, and it reproduces on main as well. The manylinux Docker image now has 3.12 beta in its list of interpreters, and I got a test failure building wheels:

```
test_number (tests.test_language_c.TestLexer.test_number) ... ok
test_symbols (tests.test_language_c.TestLexer.test_symbols) ... ok
test_bool (tests.test_language_c.TestLiteral.test_bool) ... ok
test_float (tests.test_language_c.TestLiteral.test_float) ... ok
test_int (tests.test_language_c.TestLiteral.test_int) ... python: /opt/_internal/cpython-3.12.0b1/include/python3.12/object.h:215: Py_SIZE: Assertion `ob->ob_type != &PyLong_Type' failed.
/io/scripts/build_manylinux_in_docker.sh: line 96: 220046 Aborted                 (core dumped) 
```

[Git blame](https://github.com/python/cpython/blame/3.12/Include/object.h#L215) for the assertion shows it was added in python/cpython@7559f5fda94ab568a1a910b17683ed81dc3426fb, related to python/cpython#101291.

I found the easiest way to reproduce (if you don't already have Python3.12 beta installed) was on Arch:

```bash
# install AUR python312 package which builds from source
yay -S python312

# it doesn't come with setuptools or pip...
mkdir tmp
cd tmp
cp -r /usr/lib/python3.11/site-packages/{pip,setuptools}/ .
python3.12 -m pip install --user pip setuptools
cd ..
rm -r tmp

python setup.py test
```

The coredump generated by the assertion shows the failure in [`DrgnObject_literal`](https://github.com/osandov/drgn/blob/main/libdrgn/python/object.c#L21).

### PR DESCRIPTION
**Pull request by brenns10**
Running tests on Python 3.12, we get:

test_int (tests.test_language_c.TestLiteral.test_int) ... python3.12: /usr/include/python3.12/object.h:215: Py_SIZE: Assertion `ob->ob_type != &PyLong_Type' failed. Aborted (core dumped)

We're relying on an implementation detail to check whether the object is negative. Instead, catch an overflow error, negate and try again. Genuine overflows will still overflow on the second time, but negative numbers will succeed.

### CODE REVIEW

**Comment by brenns10** [comment]
Since Python 3.12 is not on the CI yet, here's a comment to verify that I ran tests:
```
$ python3.12 setup.py test
...
Ran 663 tests in 0.693s

OK (skipped=111)
all tests passed
```

**Review by osandov — APPROVED** [review]
Assuming tests pass, this LGTM.

**Comment by brenns10** [comment]
Sorry, didn't see the message, and I didn't mean to sneak an extra commit in there :P
But I thought it might be good to add 3.12 to the CI?

**Comment by brenns10** [comment]
Ok, yeah, I thought that https://github.com/actions/setup-python had 3.12 available...
It has it listed in the releases:
https://github.com/actions/python-versions/releases

But clearly that was a mistake, I'll drop that commit 😅

**Comment by osandov** [comment]
Yeah, I think you need to ask setup-python for 3.12beta or something like that. Last time I tried this for 3.11, I couldn't find a good way to specify "the latest 3.11, whether it's alpha, beta, or released". We could always add 3.12beta (or whatever the proper syntax is), but we'd just need to remember to update it once the final version is released.

**Comment by brenns10** [comment]
Ok, makes sense. I'll stop messing with this branch but might send another PR if I find a way to do "3.12 beta or latest".

**Comment by brenns10** [comment]
I tried the syntax `3.12.0-beta.1 - 3.12`, as a use of the [hyphen ranges](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-input). You can see the [result](https://github.com/brenns10/drgn/actions/runs/5149070392/jobs/9271605107) -- it  fails as expected since I based the branch on the previous main. Not sure if it'll work generally but I'll rebase and post the PR after the CI rate limits settle :/

**Pull request merged**
