### PR TITLE
Add drgn_error_catch() - take 2

### PR DESCRIPTION
**Pull request by brenns10**
I had opened a PR a while back for a new static inline, `drgn_error_catch()`, that makes it easier to catch all errors of a specific code, and destroy them. I tried to convert a bunch of users in that PR which made it go stale super quick. I don't really think that it's necessary to convert a bunch all in one go. So this PR just adds the helper, and does an example conversion in `libdrgn/linux_kernel_helpers.c`. That ensures that we can see how it's used and catch any errors, but it also won't conflict with the module API branch (I double-checked), and shouldn't go stale so quickly.

I think this would be a nice thing to have in general. It's also related to some of the preparatory commits I have for the CTF branch, and I figured it would be nice to keep closer to upstream by adding this now.

### CODE REVIEW

**Comment by osandov** [comment]
Looks good to me conceptually, although there's a build error (which apparently makes the CI action get stuck. Oops.)

**Comment by brenns10** [comment]
How embarrassing, I swear I built and ran this, but I must not have had the `linux_kernel_helpers.c` changes applied yet. I've fixed the build error and now actually tested loading a vmcore and /proc/kcore with this, as well as running vmtests against 6.12.

**Review by osandov — COMMENTED** [review]
Oh, I just noticed that the new function is in `drgn.h`. Do you need it to be public? If not, let's move it to be internal in `error.h`. Other than that, LGTM.

**Comment by brenns10** [comment]
Nope, I don't need a public API (we don't currently even release `drgn-devel`). I'll move it!

**Pull request merged**
